#!/bin/bash
#
###############################################
# Kibojoe Linux				      #
# Version 1-1				      #
# Updated Nov. 2017			      #
# Name basic_clean ; Basic Cleaning	      #
# Use chmod +x basic_clean ; /usr/bin/kibojoe #
# Credit Holmes (Kibojoe Linux)		      #
# Site http://kibojoe.org                     #
# License Copyleft			      #
###############################################

sudo rm -rf /root/.local/share/Trash/files	# Empty trash root
sudo rm -rf /root/.local/share/Trash/info	# Empty trash root
rm -rf ~/.local/share/Trash/*
rm -rf ~/.cache/*
rm -rf ~/.adobe/*				# Flash crap
rm -rf ~/.macromedia/*				# Flash crap
rm -rf ~/.dbus/*
rm -rf ~/.thumbnails/*
rm -rf ~/.java/*
rm -rf ~/.pulse/*
rm -rf ~/.gconf/*
rm -rf ~/.gconfd/*
rm -rf ~/.parallel/*
rm -rf ~/wget*					# Polluted wget-log files

echo "Done basic cleaning...!"
sleep 2
read
clear && kill -9 -$PPID
;;
