#!/usr/bin/env bash
#
##############################################
# Kibojoe Linux				     #
# Version 1	 		             #
# Updated Dez. 2017	 		     #
# Name leavejwm ; Leave Kibojoe System       #
# Use chmod +x leave_jwm ; /usr/bin/kibojoe  #
# Credits ArchLabs			     #
# Site https://archlabslinux.com/            #
# Adapted Holmes (Kibojoe Linux)	     #
# Site http://kibojoe.org                    #
# License Copyleft 			     #
##############################################

question=$(echo "✓ Cancel|✓ Log out|✓ Lock|✓ Power off|✓ Reboot|✓ Suspend" | rofi -sep "|" \
    -dmenu -i -p 'Log out user? ' "" -width 16 -hide-scrollbar -font "Cantarell 10" \
    -eh 1 -line-padding 6 -padding 16 -no-config -lines 6 -color-enabled \
    -color-window "#444444, #444444, #444444" \
    -color-normal "#444444, #e5e5e5, #444444, #6d6d6d, #444444")

case $question in
    *Cancel)
        clear
        ;;  
    *Log out)
        jwm -exit
        ;;
    *Lock)
        i3lock -c 444444
        ;;
    *Power off)
        systemctl poweroff
        ;;
    *Reboot)
        systemctl reboot
        ;;
    *Suspend)
        systemctl suspend
        ;;
 
esac
