#!/bin/sh
#
##################################################################
# Kibojoe Linux 			                         #
# Updated 22.07.2017 21:55:02 		                         #
# Version 0.1-2 			                         #
# Name upnotifier ; Update Notifier                              #
# Use chmod +x upnotifier ; /usr/bin/                            #
# Credits Chrysostomus and deadguy [code pacaur] (Manjaro Linux) #
# Site http://polr.me/1gmk                                       #
# Adapted Holmes (Kibojoe Linux)		                 #
# Site http://kibojoe.org                                        #
# License Copyleft                                               #
##################################################################

trap 'rm /tmp/{pacmanupdates,aurupdates} 2>/dev/null' INT TERM QUIT EXIT
   nb_pac=$(checkupdates | tee /tmp/pacmanupdates | wc -l)
if [ -f /usr/bin/yaourt ]; then
   nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
else
   nb_aur=0
fi

if [ -f /usr/bin/pacaur ]; then
    nb_aur=$(pacaur -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
else
    nb_aur=0
fi

if ((nb_pac>0 || nb_aur>0)); then
  ((nb_aur>0)) && nb_aur="+ ${nb_aur}"
  ((nb_aur==0)) && unset nb_aur
  notify-send "Hello, ${nb_pac} ${nb_aur} updates for Kibojoe Linux!"
else
   nb_pac=0
   nb_aur=0
   notify-send "Hello, your Kibojoe Linux is up to date!"
fi
